Reports/Reports/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Mvc;
using Reports.Domain;
using Reports.Domain.Entities;

namespace Reports.Controllers
{
    public class ItemsController : Controller
    {
        private readonly DataManager dataManager;

        public ItemsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        public IActionResult Create(int id)
        {
            Report? report = dataManager.Reports.GetEntityById(id);
            if (report != null)
            {
                List<Item> items = new();
                if (report.ItemsCount != 0)
                { 
                    for (int i = 1; i <= report.ItemsCount - report.Items.Count; i++)
                    {
                        items.Add(new Item() { } );
                    }  
                }
                return View(items);
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Create(List<Item> entities, int id)
        {
            if (ModelState.IsValid)
            {
                Report? report = dataManager.Reports.GetEntityById(id);
                if (report != null)
                {
                    foreach (Item entity in entities)
                    {
                        report.Items.Add(entity);  
                    }
                    dataManager.Reports.UpdateEntity(report);
                }
                return RedirectToAction("Index", "Home");
            }
            return View(entities);
        }

        public IActionResult Edit(int id)
        {
            Report? report = dataManager.Reports.GetEntityById(id);

            return View(report.Items);
        }

        [HttpPost]
        public IActionResult Edit(List<Item> entities, int id)
        {
            if (ModelState.IsValid)
            {
                Report? report = dataManager.Reports.GetEntityById(id);
                if (report != null)
                {
                    report.Items.Clear();
                    foreach (Item entity in entities)
                    {
                        report.Items.Add(entity);
                    }
                    dataManager.Reports.UpdateEntity(report);
                }
                return RedirectToAction("Index", "Home");
            }
            return View(entities);
        }
    }
}

Reports/Reports/Views/Items/Create.cshtml
@model List<Item>

<div>
    <h2>Создание товаров</h2>
    <div>
        <form asp-controller="Items" asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All"></div>
            @if (Model.Count != 0)
            {
                @for (int i = 0; i < Model.Count; i++)
                {
                    <div class="div-box">
                        <label asp-for="@Model[i].Name"></label>
                        <input asp-for="@Model[i].Name" />
                        <span asp-validation-for="@Model[i].Name"></span>
                    </div>
                    <div class="div-box">
                        <label asp-for="@Model[i].Amount"></label>
                        <input asp-for="@Model[i].Amount" />
                        <span asp-validation-for="@Model[i].Amount"></span>
                    </div>
                }
            }
            else
            {
                <h2>Нет свободных ячеек</h2>
            }
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>

Reports/Reports/Views/Items/Edit.cshtml
@model List<Item>
<div>
    <h2>Создание товаров</h2>
    <div>
        <form asp-controller="Items" asp-action="Edit" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All"></div>
            @if (Model.Count != 0)
            {
                @for (int i = 0; i < Model.Count; i++)
                {
                    <div class="div-box">
                        <label asp-for="@Model[i].Name"></label>
                        <input asp-for="@Model[i].Name" />
                        <span asp-validation-for="@Model[i].Name"></span>
                    </div>
                    <div class="div-box">
                        <label asp-for="@Model[i].Amount"></label>
                        <input asp-for="@Model[i].Amount" />
                        <span asp-validation-for="@Model[i].Amount"></span>
                    </div>
                }
            }
            else
            {
                <h2>Нет товаров</h2>
            }
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>